# Generated by Django 5.2.3 on 2025-06-27 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='consecutive_correct',
            field=models.IntegerField(default=0, verbose_name='連続正解数'),
        ),
        migrations.AddField(
            model_name='session',
            name='difficulty',
            field=models.CharField(choices=[('normal', 'Normal'), ('hard', 'Hard')], default='normal', max_length=10, verbose_name='現在の難易度'),
        ),
        migrations.AddField(
            model_name='session',
            name='previous_difficulty',
            field=models.CharField(choices=[('normal', 'Normal'), ('hard', 'Hard')], default='normal', max_length=10, verbose_name='前回の難易度'),
        ),
        migrations.AddField(
            model_name='session',
            name='score',
            field=models.IntegerField(default=0, verbose_name='スコア'),
        ),
        migrations.AddField(
            model_name='session',
            name='session_answers',
            field=models.JSONField(default=list, verbose_name='解答履歴'),
        ),
        migrations.AddField(
            model_name='session',
            name='session_times',
            field=models.JSONField(default=list, verbose_name='解答時間履歴'),
        ),
        migrations.AlterField(
            model_name='session',
            name='correct_answers',
            field=models.IntegerField(default=0, verbose_name='正答数'),
        ),
        migrations.AlterField(
            model_name='session',
            name='total_questions',
            field=models.IntegerField(default=0, verbose_name='総問題数'),
        ),
    ]
