# Generated by Django 5.1.6 on 2025-02-09 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_google_authenticated_alter_user_groups_and_more'),
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='authentication.user', verbose_name='ユーザー'),
        ),
    ]
