# Generated by Django 5.1.6 on 2025-02-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_session_score_session_session_answers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='difficulty',
            field=models.CharField(choices=[('normal', 'Normal'), ('hard', 'Hard')], default='normal', max_length=10, verbose_name='難易度'),
        ),
    ]
