# Generated by Django 5.1.6 on 2025-02-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0003_session_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='previous_difficulty',
            field=models.CharField(choices=[('normal', 'Normal'), ('hard', 'Hard')], default='normal', max_length=10, verbose_name='前回の難易度'),
        ),
        migrations.AlterField(
            model_name='session',
            name='difficulty',
            field=models.CharField(choices=[('normal', 'Normal'), ('hard', 'Hard')], default='normal', max_length=10, verbose_name='現在の難易度'),
        ),
    ]
