# Generated by Django 5.1.6 on 2025-02-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0004_session_previous_difficulty_alter_session_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='consective_correct',
            field=models.IntegerField(default=0, verbose_name='連続正解数'),
        ),
        migrations.AddField(
            model_name='session',
            name='current_difficulty',
            field=models.CharField(choices=[('normal', 'Normal'), ('hard', 'Hard')], default='normal', max_length=10, verbose_name='現在の難易度'),
        ),
    ]
