# Generated by Django 5.1.6 on 2025-02-28 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0005_session_consective_correct_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='consective_correct',
            new_name='consecutive_correct',
        ),
        migrations.RemoveField(
            model_name='session',
            name='current_difficulty',
        ),
    ]
