# Generated by Django 5.1.5 on 2025-01-28 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='問題文')),
                ('choices', models.JSONField(verbose_name='選択肢（JSON形式）')),
                ('correct_answer', models.CharField(max_length=255, verbose_name='正解')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('normal', 'Normal'), ('hard', 'Hard')], default='normal', max_length=10, verbose_name='難易度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='問題作成日時')),
            ],
            options={
                'verbose_name': '問題',
                'verbose_name_plural': '問題',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('selected_answer', models.CharField(max_length=255, verbose_name='ユーザーの選択した回答')),
                ('is_correct', models.BooleanField(verbose_name='正解かどうか')),
                ('time_taken', models.FloatField(verbose_name='回答時間（秒）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='解答日時')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress.session', verbose_name='セッション')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question', verbose_name='問題ID')),
            ],
            options={
                'verbose_name': '解答',
                'verbose_name_plural': '解答',
            },
        ),
    ]
