# Generated by Django 5.1.6 on 2025-02-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('fundamental_theory', '基礎理論'), ('algorithm', 'アルゴリズムとプログラミング'), ('computer_system', 'コンピューターの構成要素'), ('system_software', 'システム構成要素'), ('software', 'ソフトウェア'), ('hardware', 'ハードウェア'), ('user_interface', 'ユーザーインターフェース'), ('database', 'データベース'), ('network', 'ネットワーク'), ('security', 'セキュリティ'), ('system_development', 'システム開発技術'), ('software_development', 'ソフトウェア開発技術'), ('management', 'マネジメント系'), ('strategy', 'ストラテジ系')], default='fundamental_theory', max_length=50, verbose_name='カテゴリ'),
        ),
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, null=True, verbose_name='解説'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='正解かどうか'),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('normal', 'Normal'), ('hard', 'Hard')], default='normal', max_length=10, verbose_name='難易度'),
        ),
    ]
