# Generated by Django 5.1.6 on 2025-02-28 18:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_question_category_question_explanation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='awarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
    ]
