# Generated by Django 5.1.6 on 2025-02-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_point_alter_user_email'),
        ('rewards', '0002_alter_badge_unique_together_remove_badge_acquired_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='point',
            new_name='points',
        ),
        migrations.AddField(
            model_name='user',
            name='badges',
            field=models.ManyToManyField(blank=True, related_name='earned_users', to='rewards.badge', verbose_name='バッジ'),
        ),
    ]
