# Generated by Django 5.1.6 on 2025-02-18 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('fundamental_theory', '基礎理論'), ('algorithm', 'アルゴリズムとプログラミング'), ('computer_system', 'コンピューターの構成要素'), ('system_software', 'システム構成要素'), ('software', 'ソフトウェア'), ('hardware', 'ハードウェア'), ('user_interface', 'ユーザーインターフェース'), ('database', 'データベース'), ('network', 'ネットワーク'), ('security', 'セキュリティ'), ('system_development', 'システム開発技術'), ('software_development', 'ソフトウェア開発技術'), ('management', 'マネジメント系'), ('strategy', 'ストラテジ系')], max_length=50, verbose_name='カテゴリ')),
                ('level', models.CharField(choices=[('bronze', 'ブロンズ'), ('silver', 'シルバー'), ('gold', 'ゴールド')], max_length=10, verbose_name='ランク')),
                ('acquired_at', models.DateTimeField(auto_now_add=True, verbose_name='獲得日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='badges')),
            ],
            options={
                'unique_together': {('user', 'category', 'level')},
            },
        ),
    ]
